# fly.toml app configuration file generated for routine-rusty-777 on 2025-07-27T13:51:10-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'routine-rusty-777'
primary_region = 'ord'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[metrics]
port = 8081
path = "/metrics"
